apiVersion: v2
name: radicale
description: A Helm chart for Radicale

type: application
version: 0.1.0
appVersion: "3.6.0.0"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2