#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
# # -- image repository
  repository: tomsquest/docker-radicale
# # -- image pull policy
  pullPolicy: IfNotPresent
# # -- image tag
  tag: 3.6.0.0

config:
  {}
# # -- Radicale configuration
# # [[ref]](https://github.com/tomsquest/docker-radicale/blob/3.6.0.0/config)
# # Example:
# # server:
# #   hosts: "0.0.0.0:5232"
# # auth:
# #   type: http_x_remote_user
# # storage:
# #   filesystem_folder: /data/collections
# # logging:
# #   level: info
# # web:
# #   type: internal
# # rights:
# #   type: owner_only

persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: external
    advancedMounts:
      main:
        main:
          - path: /data
            readOnly: false

ingress:
  main:
    enabled: false
#  # annotations:
#  #   cert-manager.io/cluster-issuer: letsencrypt-http01
#  # ingressClassName: nginx-public
    hosts:
      - host: []
#     # - host: radicale.example.com
#     # paths:
#     # - path: /
#     #   service:
#     #      identifier: http
#     #      port: http
    tls: []
#     # - secretName: radicale-cert
#     #   hosts:
#     #     - radicale.example.com