apiVersion: v2
name: bewcloud
description: A Helm chart for BewCloud

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
